var x=7;
console.log(x"+ "1="="(x+8));
console.log(x"+"+2="="(x+9));
console.log(x"+"+3="="(x+10));
console.log(x"+"+4="="(x+11));
console.log(x"+"+5="="(X+12));
console.log(x"+"+6="="(X+13));
console.log(x"+"+7="="(X+14));
console.log(x"+"+8="="(X+15));
console.log(x"+"+10="="(X+16));